// <auto-generated />
using System;
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Base.AccountBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AccountBases");

                    b.HasDiscriminator<string>("AccountType").HasValue("AccountBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Base.SecurityBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("SecurityBases");

                    b.HasDiscriminator<string>("SecurityType").HasValue("SecurityBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Base.SecurityTransactionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SecurityTransactionType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("Id");

                    b.ToTable("SecurityTransactionBases");

                    b.HasDiscriminator<string>("SecurityTransactionType").HasValue("SecurityTransactionBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Accounts.BankAccount", b =>
                {
                    b.HasBaseType("Entities.Base.AccountBase");

                    b.HasDiscriminator().HasValue("BankAccount");
                });

            modelBuilder.Entity("Entities.Accounts.GoldAccount", b =>
                {
                    b.HasBaseType("Entities.Base.AccountBase");

                    b.HasDiscriminator().HasValue("GoldAccount");
                });

            modelBuilder.Entity("Entities.Accounts.IskAccount", b =>
                {
                    b.HasBaseType("Entities.Base.AccountBase");

                    b.HasDiscriminator().HasValue("IskAccount");
                });

            modelBuilder.Entity("Entities.Accounts.MillionAccount", b =>
                {
                    b.HasBaseType("Entities.Base.AccountBase");

                    b.HasDiscriminator().HasValue("MillionAccount");
                });

            modelBuilder.Entity("Entities.Accounts.UddevallaAccount", b =>
                {
                    b.HasBaseType("Entities.Base.AccountBase");

                    b.HasDiscriminator().HasValue("UddevallaAccount");
                });

            modelBuilder.Entity("Entities.Security.MutualFund", b =>
                {
                    b.HasBaseType("Entities.Base.SecurityBase");

                    b.HasDiscriminator().HasValue("MutualFund");
                });

            modelBuilder.Entity("Entities.Security.Stock", b =>
                {
                    b.HasBaseType("Entities.Base.SecurityBase");

                    b.HasDiscriminator().HasValue("Stock");
                });

            modelBuilder.Entity("Entities.Transactions.MutualFundTransaction", b =>
                {
                    b.HasBaseType("Entities.Base.SecurityTransactionBase");

                    b.HasDiscriminator().HasValue("MutualFundTransaction");
                });

            modelBuilder.Entity("Entities.Transactions.StockTransaction", b =>
                {
                    b.HasBaseType("Entities.Base.SecurityTransactionBase");

                    b.HasDiscriminator().HasValue("StockTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
